### PR TITLE
Fix auto-naming counter and align id with name when creating new entity

### PR DESCRIPTION
**Pull request by martin-fleck-at**
- Add tests for utility functions

Fixes https://github.com/CrossBreezeNL/crossmodel/issues/48

### CODE REVIEW

**Comment by harmen-xb** [comment]
@martin-fleck-at 

Changes look good, the behaviour on attribute is indeed as expected.

Two things I notice:
- When creating an entity via the diagram, I cannot type the entity name before the actual entity is created (like I can via explorer, or like when adding attribute via the form). This means the ID of the Entity will be NewEntity, NewEntity1, etc.
- When creating an entity with the ID NewEntity, adding some attributes and saving. And then removing the Entity, save. And then add a new Entity 'NewEntity' the deleted Entity is kinda re-used somehow, bevause the NewEntity has the attributes from the removed entity.

**Comment by martin-fleck-at** [comment]
@harmen-xb Thank you for the review! The first thing I can re-produce. I'll see what we can do about that in the short-term to make that nicer. However, the second point, i cannot really reproduce. Does that happen in the diagram or what is the exact workflow here?

**Comment by harmen-xb** [comment]
@martin-fleck-at 

To reproduce:
1. Create an entity via a system diagram without changig the name.
1. Add some attributes to the entity and save.
1. Remove the new entity from the diagram and object explorer.
1. Add a new Entity via the diagram without specifying a name

Obervation: In the entity created in the last step attributes are already there as if the deleted entity object is re-used.

**Comment by martin-fleck-at** [comment]
@harmen-xb I had a deeper look into this and managed to fix both problems.

**Comment by harmen-xb** [comment]
@martin-fleck-at This indeed works better :)

Is it possible to write the new entity file after the name is typed in the diagram? Cause now when you add a new entity to a diagram the 'NewEntity' file is already created (before typing the real name of the entity). Would be nice if file name would be the same as the ID.

**Comment by martin-fleck-at** [comment]
@harmen-xb I think I could look into that but it would be like developing a complete new tool so it might be some effort. Would it be an idea to simply rename the file according to the new name, similar to what Java usually proposes?

**Comment by harmen-xb** [comment]
> @harmen-xb I think I could look into that but it would be like developing a complete new tool so it might be some effort. Would it be an idea to simply rename the file according to the new name, similar to what Java usually proposes?

@martin-fleck-at Yes, if you could rename the file if the `Id `changes that would be great! This would in the end be a generic behaviour for all files to rename the file if the Id changes. So we could also pick this up in a separate branch.

**Comment by martin-fleck-at** [comment]
@harmen-xb Great, should we create a ticket for this and then merge this PR?

**Review by harmen-xb — APPROVED** [review]
Code changs look good.

**Comment by harmen-xb** [comment]
> @harmen-xb Great, should we create a ticket for this and then merge this PR?

Yes, I reviewed code and approved it.

**Pull request merged**
