### PR TITLE
Upgrade to Langium 2.1.3

### PR DESCRIPTION
**Pull request by martin-fleck-at**
Langium > 2.0.0 only supports ESM so we refactor the extension to ESM

Setup Changes
- Set type to 'module' in package.json and update configs accordingly
- Use esbuild to develop in ESM but compile to CJS for VSX

Code Changes
- Adapt all relative imports to use '.js' extension (even for '.ts')
- Remove now obsolete adaptations of workspace manager

Test Changes
- Provide custom Jest configuration for ES modules
- Use 'jest.useFakeTimers()' as specified in Jest documentation for ESM
- Add '--experimental-vm-modules' Node flag to ESM test executions
- Add 'NODE_NO_WARNINGS' environment variable to ignore ESM warning
- Use unique report file names as we need to run twice (CJS, ESM)
- Add display name to all test configs for nicer output
- Adapt launch configs to properly debug single test or all tests

### CODE REVIEW

**Comment by harmen-xb** [comment]
@martin-fleck-at What to do with this PR?

**Comment by harmen-xb** [comment]
@martin-fleck-at If you rename the branch to feature/* the workflow will be triggered.

**Comment by martin-fleck-at** [comment]
@harmen-xb Right, I tend to forget that, sorry!

**Comment by martin-fleck-at** [comment]
Closing in favor of https://github.com/CrossBreezeNL/crossmodel/pull/40

**Pull request closed without merging**
